version: "3.8"

services:
  tu-mayordomo-app:
    container_name: tu-mayordomo-app
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:3050:80" # Expuesto a localhost por protocolo, libre de conflictos
    networks:
      - shared-proxy

networks:
  shared-proxy:
    external: true